import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import UserProvider from "@/context/user.context";
import { cookies } from "next/headers";
import ChatBot from "@/components/chat/chat-bot";
import Header from "@/components/global/header";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Comultrasan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = cookies().get("theme")?.value == "dark" ? "dark" : "";

  return (
    <html lang="en" className={theme}>
      <body className={inter.className}>
        <UserProvider>
          <Toaster />
          <Header isDarkMode={theme === "dark"} />
          {children}
          <ChatBot />
        </UserProvider>
      </body>
    </html>
  );
}
