import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import UserProvider from "@/context/user.context";
import { cookies } from "next/headers";
import ChatBot from "@/components/chat/chat-bot";
import Header from "@/components/global/header";
import { Toaster } from "react-hot-toast";
import { createClient } from "@/utils/supabase/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Comultrasan",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();

  let user = null;

  try {
    const supabase = createClient(cookieStore);

    const cookie = cookieStore.get("comultrasan")?.value;

    const { data, error } = await supabase
      .from("users")
      .select()
      .eq("id_user", cookie)
      .limit(1)
      .single();

    user = data;
  } catch (error) {
    console.log(error);
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider user={user}>
          <Toaster />
          <Header />
          {children}
          <ChatBot />
        </UserProvider>
      </body>
    </html>
  );
}
